services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: no
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sonny
      - MONGO_INITDB_ROOT_PASSWORD=sonny

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: no
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=sonny
      - ME_CONFIG_MONGODB_ADMINPASSWORD=sonny
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo: {}